import type { Attribution } from '../../types'
import data from '../../../../shared/fixtures/code_run/attribution.json'

// Real monitor-derived attribution for the coding run (generated by agent.code.export_run).
export const STUB_ATTRIBUTION: Attribution = data as unknown as Attribution
