/**
 * Dashboard first-paint data — sourced from shared/fixtures/claim_adjudication/
 * (generated by `python -m agent.domains.export_run`).
 */
export { loadFixtureTrace as loadStubMultiAgentTrace } from './loadFixture'
export { STUB_ATTRIBUTION as STUB_MULTI_ATTRIBUTION } from './stubAttribution'
